/*
Copyright 2018 Samsung SDS Cloud Native Computing Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/maratoid/jenkins-operator/pkg/apis/jenkins/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// JenkinsJobLister helps list JenkinsJobs.
type JenkinsJobLister interface {
	// List lists all JenkinsJobs in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.JenkinsJob, err error)
	// JenkinsJobs returns an object that can list and get JenkinsJobs.
	JenkinsJobs(namespace string) JenkinsJobNamespaceLister
	JenkinsJobListerExpansion
}

// jenkinsJobLister implements the JenkinsJobLister interface.
type jenkinsJobLister struct {
	indexer cache.Indexer
}

// NewJenkinsJobLister returns a new JenkinsJobLister.
func NewJenkinsJobLister(indexer cache.Indexer) JenkinsJobLister {
	return &jenkinsJobLister{indexer: indexer}
}

// List lists all JenkinsJobs in the indexer.
func (s *jenkinsJobLister) List(selector labels.Selector) (ret []*v1alpha1.JenkinsJob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.JenkinsJob))
	})
	return ret, err
}

// JenkinsJobs returns an object that can list and get JenkinsJobs.
func (s *jenkinsJobLister) JenkinsJobs(namespace string) JenkinsJobNamespaceLister {
	return jenkinsJobNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// JenkinsJobNamespaceLister helps list and get JenkinsJobs.
type JenkinsJobNamespaceLister interface {
	// List lists all JenkinsJobs in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.JenkinsJob, err error)
	// Get retrieves the JenkinsJob from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.JenkinsJob, error)
	JenkinsJobNamespaceListerExpansion
}

// jenkinsJobNamespaceLister implements the JenkinsJobNamespaceLister
// interface.
type jenkinsJobNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all JenkinsJobs in the indexer for a given namespace.
func (s jenkinsJobNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.JenkinsJob, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.JenkinsJob))
	})
	return ret, err
}

// Get retrieves the JenkinsJob from the indexer for a given namespace and name.
func (s jenkinsJobNamespaceLister) Get(name string) (*v1alpha1.JenkinsJob, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("jenkinsjob"), name)
	}
	return obj.(*v1alpha1.JenkinsJob), nil
}
