/*
Copyright 2018 Samsung SDS Cloud Native Computing Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/maratoid/jenkins-operator/pkg/apis/jenkins/v1alpha1"
	scheme "github.com/maratoid/jenkins-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JenkinsInstancesGetter has a method to return a JenkinsInstanceInterface.
// A group's client should implement this interface.
type JenkinsInstancesGetter interface {
	JenkinsInstances(namespace string) JenkinsInstanceInterface
}

// JenkinsInstanceInterface has methods to work with JenkinsInstance resources.
type JenkinsInstanceInterface interface {
	Create(*v1alpha1.JenkinsInstance) (*v1alpha1.JenkinsInstance, error)
	Update(*v1alpha1.JenkinsInstance) (*v1alpha1.JenkinsInstance, error)
	UpdateStatus(*v1alpha1.JenkinsInstance) (*v1alpha1.JenkinsInstance, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.JenkinsInstance, error)
	List(opts v1.ListOptions) (*v1alpha1.JenkinsInstanceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JenkinsInstance, err error)
	JenkinsInstanceExpansion
}

// jenkinsInstances implements JenkinsInstanceInterface
type jenkinsInstances struct {
	client rest.Interface
	ns     string
}

// newJenkinsInstances returns a JenkinsInstances
func newJenkinsInstances(c *JenkinsV1alpha1Client, namespace string) *jenkinsInstances {
	return &jenkinsInstances{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the jenkinsInstance, and returns the corresponding jenkinsInstance object, and an error if there is any.
func (c *jenkinsInstances) Get(name string, options v1.GetOptions) (result *v1alpha1.JenkinsInstance, err error) {
	result = &v1alpha1.JenkinsInstance{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jenkinsinstances").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of JenkinsInstances that match those selectors.
func (c *jenkinsInstances) List(opts v1.ListOptions) (result *v1alpha1.JenkinsInstanceList, err error) {
	result = &v1alpha1.JenkinsInstanceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jenkinsinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested jenkinsInstances.
func (c *jenkinsInstances) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("jenkinsinstances").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a jenkinsInstance and creates it.  Returns the server's representation of the jenkinsInstance, and an error, if there is any.
func (c *jenkinsInstances) Create(jenkinsInstance *v1alpha1.JenkinsInstance) (result *v1alpha1.JenkinsInstance, err error) {
	result = &v1alpha1.JenkinsInstance{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("jenkinsinstances").
		Body(jenkinsInstance).
		Do().
		Into(result)
	return
}

// Update takes the representation of a jenkinsInstance and updates it. Returns the server's representation of the jenkinsInstance, and an error, if there is any.
func (c *jenkinsInstances) Update(jenkinsInstance *v1alpha1.JenkinsInstance) (result *v1alpha1.JenkinsInstance, err error) {
	result = &v1alpha1.JenkinsInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jenkinsinstances").
		Name(jenkinsInstance.Name).
		Body(jenkinsInstance).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *jenkinsInstances) UpdateStatus(jenkinsInstance *v1alpha1.JenkinsInstance) (result *v1alpha1.JenkinsInstance, err error) {
	result = &v1alpha1.JenkinsInstance{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jenkinsinstances").
		Name(jenkinsInstance.Name).
		SubResource("status").
		Body(jenkinsInstance).
		Do().
		Into(result)
	return
}

// Delete takes name of the jenkinsInstance and deletes it. Returns an error if one occurs.
func (c *jenkinsInstances) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jenkinsinstances").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *jenkinsInstances) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jenkinsinstances").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched jenkinsInstance.
func (c *jenkinsInstances) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JenkinsInstance, err error) {
	result = &v1alpha1.JenkinsInstance{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("jenkinsinstances").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
