type: chart
builds:
  - image: samsung_cnct/jenkins-operator
    context: jenkins-operator
    chart: jenkins-operator
    tagValue: image.tag
    dockerContext: .
deployments:
  - chart: jenkins-operator
    timeout: 600
    retries: 2
    release: jenkins-operator
prod:
  doDeploy: none
