apiVersion: jenkins.jenkinsoperator.samsung-cnct.github.com/v1alpha2
kind: JenkinsInstance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: jenkinsinstance-sample
spec:
  image: "jenkins/jenkins:lts"
  imagepullpolicy: Always
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  env:
    SOME_ENV: "test"
  plugins:
    - id: cloudbees-folder
      version: "6.8"
    - id: build-blocker-plugin
      version: 1.7.3
    - id: authorize-project
      version: 1.3.0
    - id: kubernetes
      version: latest
  cascconfig:
    configmap: jenkins-config
  cascsecret: jenkins-admin-secret
  groovysecret: jenkins-groovy-secret
  annotations:
    cnct.io/annotation: "test"
    cnct.io/other-annotation: "other test"
  executors: 5
  adminsecret: jenkins-admin-secret
  service:
    name: jenkins
    servicetype: NodePort
    annotations:
      cnct.io/service-annotation: "test"
      cnct.io/other-service-annotation: "other test"
  storage:
    jobspvc: jenkins
    jobspvcspec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  nodeselector:
    "kubernetes.io/hostname": minikube
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: "kubernetes.io/hostname"
              operator: In
              values:
                - minikube

