/*
Copyright 2018 Samsung SDS Cloud Native Computing Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/maratoid/jenkins-operator/pkg/apis/jenkins/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJenkinsPlugins implements JenkinsPluginInterface
type FakeJenkinsPlugins struct {
	Fake *FakeJenkinsV1alpha1
	ns   string
}

var jenkinspluginsResource = schema.GroupVersionResource{Group: "jenkins.jenkinsoperator.maratoid.github.com", Version: "v1alpha1", Resource: "jenkinsplugins"}

var jenkinspluginsKind = schema.GroupVersionKind{Group: "jenkins.jenkinsoperator.maratoid.github.com", Version: "v1alpha1", Kind: "JenkinsPlugin"}

// Get takes name of the jenkinsPlugin, and returns the corresponding jenkinsPlugin object, and an error if there is any.
func (c *FakeJenkinsPlugins) Get(name string, options v1.GetOptions) (result *v1alpha1.JenkinsPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jenkinspluginsResource, c.ns, name), &v1alpha1.JenkinsPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JenkinsPlugin), err
}

// List takes label and field selectors, and returns the list of JenkinsPlugins that match those selectors.
func (c *FakeJenkinsPlugins) List(opts v1.ListOptions) (result *v1alpha1.JenkinsPluginList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jenkinspluginsResource, jenkinspluginsKind, c.ns, opts), &v1alpha1.JenkinsPluginList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.JenkinsPluginList{}
	for _, item := range obj.(*v1alpha1.JenkinsPluginList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jenkinsPlugins.
func (c *FakeJenkinsPlugins) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jenkinspluginsResource, c.ns, opts))

}

// Create takes the representation of a jenkinsPlugin and creates it.  Returns the server's representation of the jenkinsPlugin, and an error, if there is any.
func (c *FakeJenkinsPlugins) Create(jenkinsPlugin *v1alpha1.JenkinsPlugin) (result *v1alpha1.JenkinsPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jenkinspluginsResource, c.ns, jenkinsPlugin), &v1alpha1.JenkinsPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JenkinsPlugin), err
}

// Update takes the representation of a jenkinsPlugin and updates it. Returns the server's representation of the jenkinsPlugin, and an error, if there is any.
func (c *FakeJenkinsPlugins) Update(jenkinsPlugin *v1alpha1.JenkinsPlugin) (result *v1alpha1.JenkinsPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jenkinspluginsResource, c.ns, jenkinsPlugin), &v1alpha1.JenkinsPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JenkinsPlugin), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJenkinsPlugins) UpdateStatus(jenkinsPlugin *v1alpha1.JenkinsPlugin) (*v1alpha1.JenkinsPlugin, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(jenkinspluginsResource, "status", c.ns, jenkinsPlugin), &v1alpha1.JenkinsPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JenkinsPlugin), err
}

// Delete takes name of the jenkinsPlugin and deletes it. Returns an error if one occurs.
func (c *FakeJenkinsPlugins) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(jenkinspluginsResource, c.ns, name), &v1alpha1.JenkinsPlugin{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJenkinsPlugins) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jenkinspluginsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.JenkinsPluginList{})
	return err
}

// Patch applies the patch and returns the patched jenkinsPlugin.
func (c *FakeJenkinsPlugins) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.JenkinsPlugin, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jenkinspluginsResource, c.ns, name, data, subresources...), &v1alpha1.JenkinsPlugin{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.JenkinsPlugin), err
}
